/* eslint-disable react/prop-types */
import React from "react";
import Head from "next/head";
import type { ReactNode } from "react";
import Navbar from "../Navbar";

const BasicLayout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Steam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      {/* Footer */}
    </>
  );
};

export default BasicLayout;
